export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed-dim": "#b4c5ff",
        "outline": "#737686",
        "on-secondary-container": "#596372",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#d6e0f1",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "background": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "primary-container": "#2563eb",
        "surface-bright": "#f8f9fa",
        "secondary": "#555f6d",
        "on-surface-variant": "#434655",
        "primary": "#004ac6",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#eeefff",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#d9e3f4",
        "surface-container": "#edeeef",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3e4755",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#bc4800",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "surface-tint": "#0053db",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#360f00",
        "on-background": "#191c1d",
        "tertiary": "#943700",
        "surface": "#f8f9fa",
        "on-secondary-fixed": "#121c28",
        "on-tertiary-container": "#ffede6",
        "on-primary-fixed": "#00174b",
        "secondary-fixed-dim": "#bdc7d8",
        "inverse-on-surface": "#f0f1f2"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "16px",
        "header-height": "64px",
        "unit": "4px",
        "container-margin": "24px",
        "sidebar-width": "260px",
        "table-cell-padding": "12px 16px"
      },
      "fontFamily": {
        "display": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "mono-sm": ["Geist Mono", "monospace"]
      },
      "fontSize": {
        "display": ["30px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "mono-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
