export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "outline": "var(--color-outline)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "background": "var(--color-background)",
        "on-tertiary": "var(--color-on-tertiary)",
        "primary-container": "var(--color-primary-container)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary": "var(--color-primary)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "error": "var(--color-error)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-surface": "var(--color-on-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-background": "var(--color-on-background)",
        "tertiary": "var(--color-tertiary)",
        "surface": "var(--color-surface)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "inverse-on-surface": "var(--color-inverse-on-surface)"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "16px",
        "header-height": "64px",
        "unit": "4px",
        "container-margin": "24px",
        "sidebar-width": "260px",
        "table-cell-padding": "12px 16px"
      },
      "fontFamily": {
        "display": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "mono-sm": ["Geist Mono", "monospace"]
      },
      "fontSize": {
        "display": ["30px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "mono-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
