version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chaos-planner-db
    environment:
      POSTGRES_DB: chaos_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: chaos-planner-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chaos_planner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=nakkasohankumar@gmail.com
      - SMTP_PASSWORD=ntoi zqjr zodu pxus
      - MAIL_FROM=nakkasohankumar@gmail.com
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chaos-planner-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
